name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  goVersion: "1.25"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu]
        arch: [amd64, arm64]
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.goVersion }}

      - name: Test
        run: go test ./...
